{{ if .Values.postgres.external_postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-geonode-external-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.postgres.username | b64enc }}
  password: {{ .Values.postgres.external_postgres.geonode_password | b64enc }}
{{ end }}
