
{{- if eq .Values.postgres.type "operator" -}}
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: "{{ include "postgres_pod_name" . }}"
  {{- if .Values.postgres.operator.annotations }}
  annotations:
    {{- toYaml .Values.postgres.operator.annotations | nindent 4 }}
  {{- end }}
spec:
  {{ if .Values.postgres.operator.env }}
  env:
    {{- toYaml .Values.postgres.operator.env | nindent 4 }}
  {{- end }}
  teamId: {{ .Release.Name | quote }}
  volume:
    size: {{ .Values.postgres.operator.storageSize }}
    storageClass: {{ .Values.postgres.operator.storageClass }}
  enableMasterLoadBalancer: {{ .Values.postgres.operator.enableMasterLoadBalancer }}
  allowedSourceRanges: {{- toYaml .Values.postgres.operator.allowedSourceRanges | nindent 4 }}
  numberOfInstances: {{ int .Values.postgres.operator.numberOfInstances }}
  users:
    {{ .Values.postgres.username }}:
    - superuser
    {{ .Values.postgres.geonode_databasename_and_username }}:
    - superuser
    - createdb
    - login
    {{ .Values.postgres.geodata_databasename_and_username }}:
    - superuser
    - createdb
    - login
  databases:
    {{ .Values.postgres.geonode_databasename_and_username }}: {{ .Values.postgres.geonode_databasename_and_username }}
    {{ .Values.postgres.geodata_databasename_and_username }}: {{ .Values.postgres.geodata_databasename_and_username }}
  preparedDatabases:
    {{ .Values.postgres.geodata_databasename_and_username }}:
      schemas:
        {{ .Values.postgres.schema }}: {}
      extensions:
        pg_partman: {{ .Values.postgres.schema }}
        postgis: {{ .Values.postgres.schema }}
    {{ .Values.postgres.geodata_databasename_and_username }}:
      schemas:
        {{ .Values.postgres.schema }}: {}
      extensions:
        pg_partman: {{ .Values.postgres.schema }}
        postgis: {{ .Values.postgres.schema }}
  postgresql:
    {{- if .Values.postgres.operator.parameters }}
    parameters: {{- toYaml .Values.postgres.operator.parameters | nindent 6 }}
    {{- end }}
    version: {{ .Values.postgres.operator.postgres_version | quote }}

  {{- if .Values.postgres.operator.patroni }}
  patroni: {{- toYaml .Values.postgres.operator.patroni | nindent 4 }}
  {{- end }}
  resources: {{ toYaml .Values.postgres.operator.resources | nindent 4 }}
  {{- if .Values.postgres.operator.clone }}
  clone: {{- toYaml .Values.postgres.operator.clone | nindent 4 }}
  {{- end }}
{{ end }}
