{{ if and .Values.postgres.external_postgres.enabled (not .Values.postgres.external_postgres.secret.existingSecretName )}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-external-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  postgres_username: {{ .Values.postgres.username | b64enc }}
  postgres_password: {{ .Values.postgres.external_postgres.secret.postgres_password | b64enc }}
{{ end }}
