{{ if .Values.postgres.external_postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-geodata-external-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.postgres.geodata_databasename_and_username | b64enc }}
  password: {{ .Values.postgres.external_postgres.geodata_password | b64enc }}
{{ end }}
