{{ if and .Values.postgres.external_postgres.enabled (not .Values.postgres.external_postgres.secret.existingSecretName )}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-geonode-external-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  geonode_username: {{ .Values.postgres.geonode_databasename_and_username | b64enc }}
  geonode_password: {{ .Values.postgres.external_postgres.secret.geonode_password | b64enc }}
{{ end }}
