# default values for minikube deployment of geonode 5.1.0

global:
  storageClass: standard

geonode:
  replicaCount: 1 # not working yet
  imagePullPolicy: IfNotPresent

  general:
    debug: True
    debug_static: True
    externalScheme: http
    externalDomain: geonode.local

  persistant:
    storageSize: 2Gi

  ingress:
    enabled: False

  secret:
    superUser:
      password: geonode

  mail:
    enabled: False

  register:
    open_signup: True
    email_verification: "none"
    authentication_method: username_email

# if you want to deploy with self build geoserver image
# geoserver:
#   securityContext:
#     runAsNonRoot: true
#     fsGroup: 1000
#     runAsUser: 1000
#     runAsGroup: 1000
#   image:
#   # best to build your own non root contaier image
#     name: <YourRepository>/geoserver-nonroot
#     tag: 2.28.4-latest

pycsw:
  enabled: True

# This deploys postgres operator into your cluster
postgres-operator:
  enabled: True

postgres:
  type: operator
  operator:
    storageSize: 2Gi
    numberOfInstances: 1
    postgres_version: 15
    storageClass: standard
    enableMasterLoadBalancer: False

# alternative way to run geonode-k8s is with external postgres/postgis database 
# postgres:
#   type: external
#   username: postgres
#   geonode_databasename_and_username: geonode
#   geodata_databasename_and_username: geodata

#   external:
#     hostname: "external-postgres.com"
#     port: 5432
#     secret:
#       postgres_password:
#       geonode_password:
#       geodata_password:

redis:
  enabled: True
  persistence:
    enabled: False
  image:
    name: redis
    tag: "8.4.0"
    # override digest included in redis subchart, to allow using other registries
    digest: ""
    pullPolicy: IfNotPresent

rabbitmq:
  enabled: False

memcached:
  image:
    repository: memcached
    tag: "1.6.40"
    pullPolicy: IfNotPresent
  metrics:
    image:
      pullPolicy: IfNotPresent
