apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geoserver_pod_name" . }}-env
  namespace: {{ .Release.Namespace }}
data:
  GEONODE_LB_HOST_IP: {{ .Values.geonode.ingress.externalDomain | quote }}
  GEONODE_LB_PORT: {{ .Values.geonode.ingress.externalPort | quote }}
  GEONODE_HOST_IP: localhost

  PUBLIC_PORT: {{ .Values.geonode.ingress.externalPort | quote }}
  DJANGO_URL: http://{{ include "geonode_pod_name" .}}/
  ENABLE_JSONP: 'true'
  outFormat: text/javascript
  #GEOSERVER_JAVA_OPTS: "-Djava.awt.headless=true -Xms2G -Xmx4G -Dgwc.context.suffix=gwc -XX:+UnlockDiagnosticVMOptions -XX:+LogVMOutput -XX:LogFile=/var/log/jvm.log -XX:PerfDataSamplingInterval=500 -XX:SoftRefLRUPolicyMSPerMB=36000 -XX:-UseGCOverheadLimit -XX:+UseConcMarkSweepGC -XX:ParallelGCThreads=4 -Dfile.encoding=UTF8 -Djavax.servlet.request.encoding=UTF-8 -Djavax.servlet.response.encoding=UTF-8 -Duser.timezone=GMT -Dorg.geotools.shapefile.datetime=false -DGEOSERVER_CSRF_DISABLED=true -DPRINT_BASE_URL=http://geoserver:8080/geoserver/pdf -DALLOW_ENV_PARAMETRIZATION=true -Xbootclasspath/a:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/marlin-0.9.3-Unsafe.jar -Dsun.java2d.renderer=org.marlin.pisces.MarlinRenderingEngine"
  GEOSERVER_JAVA_OPTS: -Djava.awt.headless=true -Xms2G -Xmx4G -XX:+UnlockDiagnosticVMOptions -XX:+LogVMOutput -XX:LogFile=/var/log/jvm.log -XX:PerfDataSamplingInterval=500 -XX:SoftRefLRUPolicyMSPerMB=36000 -XX:-UseGCOverheadLimit -XX:+UseConcMarkSweepGC -XX:ParallelGCThreads=4 -Dfile.encoding=UTF8 -Djavax.servlet.request.encoding=UTF-8 -Djavax.servlet.response.encoding=UTF-8 -Duser.timezone=GMT -Dorg.geotools.shapefile.datetime=false -DGEOSERVER_CSRF_DISABLED=true -DPRINT_BASE_URL=http://geoserver:8080/geoserver/pdf -DALLOW_ENV_PARAMETRIZATION=true -Xbootclasspath/a:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/marlin-0.9.3-Unsafe.jar -Dsun.java2d.renderer=org.marlin.pisces.MarlinRenderingEngine
  NGINX_BASE_URL: "{{ include "public_url" . }}/"

  DATABASE_HOST: "{{ include "postgres_pod_name" . }}"
  DATABASE_PORT: "{{ include "database_port" . }}"
  GEONODE_GEODATABASE: {{ .Values.postgres.geodatabasename | quote  }}
  GEONODE_GEODATABASE_SCHEMA: {{ .Values.postgres.schema | quote }}

  GEOSERVER_ADMIN_USER: {{ .Values.geoserver.admin_username | quote }}
  GEOSERVER_ADMIN_PASSWORD: {{ .Values.geoserver.admin_password | quote }}