# geoserver stateful set
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-geoserver
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      org.geonode.instance: {{ .Release.Name }}-geoserver
  serviceName: {{ .Release.Name }}-geoserver
  replicas: {{ .Values.nginx.replicas }}
  template:
    metadata:
      labels:
        org.geonode.instance: {{ .Release.Name }}-geoserver
    spec:
      terminationGracePeriodSeconds: 3
      initContainers:
      - name: data-dir-conf
        image: geonode/geoserver_data:{{ .Values.geoserver.image.tag }}
        command:
        - sh
        - -c
        - |
          # Copy defaults from data container
          cp -r /tmp/geonode/downloaded/data /geoserver_data

          # Copy overrides from ConfigMap
          cp /overrides/notifier.xml /geoserver_data/data/notifier/

          # Update custom EPSG codes
          cat /geoserver_data/data/user_projections/epsg.properties > /tmp/epsg.properties
          {{- range .Values.geoserver.customEPSGs }}
          echo '{{ . }}' >> /tmp/epsg.properties
          {{- end }}
          {{- range .Values.geoserver.extraCustomEPSGs }}
          echo '{{ . }}' >> /tmp/epsg.properties
          {{- end }}
          sort -u /tmp/epsg.properties > /geoserver_data/data/user_projections/epsg.properties
        volumeMounts:
        - name: persistence
          mountPath: /geoserver_data/data
          subPath: geoserver-data-dir
        - name: geoserver-notifier-xml
          mountPath: /overrides

      containers:
      - name: geoserver
        image: "{{ .Values.geoserver.image.name }}:{{ .Values.geoserver.image.tag }}"
        # command: 
        #   - tail
        #   - -f
        #   - /dev/null
        ports:
        - containerPort: {{ include "geoserver_port" . }}
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-geoserver-env
        volumeMounts:
        - name: persistence
          mountPath: /geoserver_data/data
          subPath: geoserver-data-dir
        readinessProbe:
          tcpSocket:
            port: {{ include "geoserver_port" . }}
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 15
        livenessProbe:
          tcpSocket:
            port: {{ include "geoserver_port" . }}
          initialDelaySeconds: 180
          periodSeconds: 5
          failureThreshold: 15
        # resources:
        #   requests:
        #     memory: 2Gi
        #     cpu: 100m
        #   limits:
        #     memory: 4Gi
        #     cpu: 400m
      volumes:
      - name: geoserver-notifier-xml
        configMap:
          name: {{ .Release.Name }}-geoserver-notifier-xml
      - name: persistence
        persistentVolumeClaim:
          claimName: pvc-{{ .Release.Name }}-geonode
