apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Release.Name }}-statics
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - {{ .Values.global.accessMode }}
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: 2Gi
