apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
data:
  GEOSERVER_ADMIN_PASSWORD: {{ b64enc "geoserver" }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc }}
  GEONODE_DATABASE_PASSWORD: {{ .Values.postgresql.password | b64enc }}
  GEONODE_GEODATABASE_PASSWORD: {{ .Values.postgresql.password | b64enc }}
  {{- range $key, $val := .Values.geonode.extraSecretEnvs }}
  {{ $key  }}: {{ b64enc $val }}
  {{- end }}
