
# env vars for Django Geonode

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-geonode-env
  namespace: {{ .Release.Namespace }}
data:
  IS_CELERY: "False"
  DOCKERIZE_VERSION: "v0.6.1"
  DEBUG: {{ include "boolean2str" .Values.geonode.general.debug | quote }}
  CLIENT_RESULTS_LIMIT: '25'
  SOCIALACCOUNT_WITH_GEONODE_LOCAL_SINGUP: "True"
  C_FORCE_ROOT: '1'
  MAX_DOCUMENT_SIZE:  {{ .Values.geonode.general.max_document_size | quote }}
  API_LIMIT_PER_PAGE: {{ .Values.geonode.general.api_limit_per_page | quote }}
  # GeoNode APIs
  API_LOCKDOWN: 'False'
  TASTYPIE_APIKEY: ""
  # TODO (mwall) set this automatically with helm magics
  {{ if  ( eq .Release.Revision 1 )}}
  IS_FIRST_START: 'True'
  {{ else }}
  IS_FIRST_START: 'False'
  {{ end }}
  FORCE_REINIT: 'False'
  # set this to true breaks upload
  ASYNC_SIGNALS: 'False'
  CACHE_BUSTING_STATIC_ENABLED: 'False'
  CACHE_BUSTING_MEDIA_ENABLED: 'False'
  DOCKER_ENV: production

  GEONODE_INSTANCE_NAME: {{ .Release.Name }}
  GEONODE_LB_HOST_IP: {{ .Values.geonode.ingress.externalDomain | quote }}
  GEONODE_LB_PORT: {{ .Values.geonode.ingress.externalPort | quote }}
  GEONODE_DB_CONN_MAX_AGE: '0'
  GEONODE_DB_CONN_TOUT: '5'

  # Rabbitmq
  BROKER_URL: "{{ include "broker_url" . }}"

  # DJANGO SITE CONF
  SITEURL: "{{ include "public_url" . }}/"
  SITE_HOST_SCHEMA: {{ .Values.geonode.ingress.externalScheme | quote }}
  ALLOWED_HOSTS: "['django', '*', '{{ .Values.geonode.ingress.externalDomain }}']"
  PROXY_ALLOWED_HOSTS: 'localhost,django,geonode,geoserver,spatialreference.org,nominatim.openstreetmap.org,dev.openlayers.org'

  # Admin Settings
  ADMIN_USERNAME: admin
  # admin password in secret
  ADMIN_EMAIL: {{ .Values.geonode.general.superUser.email | quote }}
  ADMIN_PASSWORD: {{ .Values.geonode.general.superUser.password | quote }}

  # EMAIL Notifications
  EMAIL_ENABLE:  {{  include "boolean2str" .Values.geonode.mail.enabled | quote }}
  DJANGO_EMAIL_BACKEND: {{ .Values.geonode.mail.backend | quote }}
  DJANGO_EMAIL_HOST: {{ .Values.geonode.mail.host | quote }}
  DJANGO_EMAIL_PORT: {{ .Values.geonode.mail.port | quote }}
  DJANGO_EMAIL_HOST_USER: {{ .Values.geonode.mail.user | quote }}
  DJANGO_EMAIL_HOST_PASSWORD: {{ .Values.geonode.mail.password | quote }}
  DJANGO_EMAIL_USE_TLS: {{ include "boolean2str" .Values.geonode.mail.tls | quote }}
  DJANGO_EMAIL_USE_SSL: {{ include "boolean2str" .Values.geonode.mail.use_ssl | quote }}
  DEFAULT_FROM_EMAIL: {{ .Values.geonode.mail.from | quote }}

  # PATH
  # TODO (mwall) allign with volumeMount locations
  STATIC_ROOT: /mnt/volumes/statics/static/
  MEDIA_ROOT: /mnt/volumes/statics/uploaded/
  GEOIP_PATH: /mnt/volumes/statics/geoip.db

  # Session/Access Control
  LOCKDOWN_GEONODE: 'False'
  CORS_ORIGIN_ALLOW_ALL: 'True'
  X_FRAME_OPTIONS: ALLOW-FROM ALL
  SESSION_EXPIRED_CONTROL_ENABLED: 'True'
  DEFAULT_ANONYMOUS_VIEW_PERMISSION: 'True'
  DEFAULT_ANONYMOUS_DOWNLOAD_PERMISSION: 'True'

  # Users Registration
  ACCOUNT_OPEN_SIGNUP: {{ include "boolean2str" .Values.geonode.register.open_signup | quote }}
  ACCOUNT_EMAIL_REQUIRED: {{ include "boolean2str" .Values.geonode.register.email_required | quote }}
  ACCOUNT_APPROVAL_REQUIRED: {{ include "boolean2str" .Values.geonode.register.approval_required | quote }}
  ACCOUNT_CONFIRM_EMAIL_ON_GET: {{ include "boolean2str" .Values.geonode.register.confirm_email_on_get | quote }}
  ACCOUNT_EMAIL_VERIFICATION: {{ .Values.geonode.register.email_verification | quote }}
  ACCOUNT_EMAIL_CONFIRMATION_REQUIRED: {{ include "boolean2str" .Values.geonode.register.conformation_required | quote }}
  ACCOUNT_AUTHENTICATION_METHOD: {{ .Values.geonode.register.authentication_method | quote }}
  {{ if .Values.geonode.register.registered_members_group_name }}
  REGISTERED_MEMBERS_GROUP_NAME: {{ .Values.geonode.register.registered_members_group_name | quote }}
  {{ end }}
  AUTO_ASSIGN_REGISTERED_MEMBERS_TO_REGISTERED_MEMBERS_GROUP_NAME: {{ include "boolean2str"  .Values.geonode.register.auto_assign_registered_members_to_registered | quote }}
  SHOW_PROFILE_EMAIL: {{  include "boolean2str" .Values.geonode.register.show_profile_email | quote }}
  # SOCIAL CONNECTOR
  # SOCIALACCOUNT_AUTO_SIGNUP: "False"

  # LDAP Configuration
  LDAP_ENABLED:  {{ include "boolean2str" .Values.geonode.ldap.enabled | quote }}
  LDAP_SERVER_URL: {{ .Values.geonode.ldap.uri | quote }}
  LDAP_BIND_DN: {{ .Values.geonode.ldap.bind_dn | quote }}
  LDAP_BIND_PASSWORD: {{ .Values.geonode.ldap.bind_password | quote }}
  LDAP_USER_SEARCH_DN: {{ .Values.geonode.ldap.user_search_dn | quote }}
  LDAP_USER_SEARCH_FILTERSTR: {{ .Values.geonode.ldap.user_search_filterstr | quote }}
  LDAP_ALWAYS_UPDATE_USER: {{ .Values.geonode.ldap.always_update_user | quote }}
  LDAP_MIRROR_GROUPS: {{ include "boolean2str" .Values.geonode.ldap.mirror_groups | quote }}
  LDAP_GROUP_SEARCH_DN: {{ .Values.geonode.ldap.group_search_dn | quote }}
  LDAP_GROUP_SEARCH_FILTERSTR: {{ .Values.geonode.ldap.group_search_filterstr | quote }}
  
  LDAP_USER_ATTR_MAP_FIRST_NAME: {{ .Values.geonode.ldap.attr_map_first_name | quote }}
  LDAP_USER_ATTR_MAP_LAST_NAME: {{ .Values.geonode.ldap.attr_map_last_name | quote }}
  LDAP_USER_ATTR_MAP_EMAIL_ADDR: {{ .Values.geonode.ldap.attr_map_email_addr | quote }}


  # OAuth2
  # TODO (mwall) implement OAUTH2
  OAUTH2_API_KEY: ""
  OAUTH2_CLIENT_ID: ""
  OAUTH2_CLIENT_SECRET: ""

  DJANGO_SETTINGS_MODULE: geonode.settings
  DEFAULT_BACKEND_DATASTORE: datastore
  DEFAULT_BACKEND_UPLOADER: geonode.importer

  TIME_ENABLED: 'True'
  MOSAIC_ENABLED: 'False'

  HAYSTACK_SEARCH: {{ include "boolean2str" .Values.geonode.haystack.enabled | quote }}
  HAYSTACK_ENGINE_URL: {{ .Values.geonode.haystack.engine_url | quote }}
  HAYSTACK_ENGINE_INDEX_NAME: {{ .Values.geonode.haystack.engine_index_name | quote }}
  HAYSTACK_SEARCH_RESULTS_PER_PAGE: {{ .Values.geonode.haystack.search_results_per_page | quote }}

  MEMCACHED_ENABLED: {{  include "boolean2str" .Values.geonode.memcached.enabled | quote }}
  MEMCACHED_BACKEND: django.core.cache.backends.memcached.MemcachedCache
  MEMCACHED_LOCATION: {{ .Release.Name }}-memcached
  MEMCACHED_LOCK_EXPIRE: {{ .Values.geonode.memcached.lock_expire | quote }}
  MEMCACHED_LOCK_TIMEOUT: {{ .Values.geonode.memcached.lock_timeout | quote }}

  # Monitoring
  MONITORING_ENABLED: {{  include "boolean2str" .Values.geonode.monitoring.enabled | quote }}
  MONITORING_DATA_TTL: {{ .Values.geonode.monitoring.data_tls | quote }}
  USER_ANALYTICS_ENABLED: {{  include "boolean2str" .Values.geonode.monitoring.user_analytics_enabled | quote }}
  USER_ANALYTICS_GZIP: {{  include "boolean2str" .Values.geonode.monitoring.user_analytics_gzip | quote }}
  CENTRALIZED_DASHBOARD_ENABLED: {{  include "boolean2str" .Values.geonode.monitoring.centralized_dashboard_enabled | quote }}
  MONITORING_SERVICE_NAME: {{ .Release.Name }}-monitoring
  MONITORING_HOST_NAME: {{ .Release.Name }}-monitoring

  # Other Options/Contribs
  MODIFY_TOPICCATEGORY: 'True'
  AVATAR_GRAVATAR_SSL: 'True'
  AVATAR_DEFAULT_URL: /geonode/img/avatar.png
  EXIF_ENABLED: 'True'
  CREATE_LAYER: 'True'
  FAVORITE_ENABLED: 'True'

  # GEOSERVER CONFIGURATION #
  GEOSERVER_WEB_UI_LOCATION: "{{ include "public_url" . }}/geoserver/"
  GEOSERVER_PUBLIC_LOCATION: "{{ include "public_url" . }}/geoserver/"
  GEOSERVER_PUBLIC_SCHEMA: {{ .Values.geonode.ingress.externalScheme | quote }}
  GEOSERVER_LOCATION: "http://{{ .Release.Name }}-geoserver:{{ include "geoserver_port" . }}/geoserver/"
  GEOSERVER_ADMIN_USER: "admin"
  GEOSERVER_ADMIN_PASSWORD: {{ .Values.geoserver.admin_password | quote }}

  OGC_REQUEST_TIMEOUT: '30'
  OGC_REQUEST_MAX_RETRIES: '1'
  OGC_REQUEST_BACKOFF_FACTOR: '0.3'
  OGC_REQUEST_POOL_MAXSIZE: '10'
  OGC_REQUEST_POOL_CONNECTIONS: '10'
  # GIS Client
  GEONODE_CLIENT_LAYER_PREVIEW_LIBRARY: mapstore