apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: "{{ include "postgres_container_name" . }}"
spec:
  teamId: {{ .Release.Name | quote }}
  volume:
    size: {{ .Values.postgres.operator_manifest.storageSize }}
  numberOfInstances: {{ int .Values.postgres.operator_manifest.numberOfInstances }}
  users:
    {{ .Values.postgres.username }}:
    - superuser
    {{ .Values.postgres.geonodedatabase }}:
    - superuser
    - createdb
    - login
    {{ .Values.postgres.geodatabasename }}:
    - superuser
    - createdb
    - login
  databases:
    {{ .Values.postgres.geonodedatabase }}: {{ .Values.postgres.geonodedatabase }}
    {{ .Values.postgres.geodatabasename }}: {{ .Values.postgres.geodatabasename }}
  preparedDatabases:
    {{ .Values.postgres.geodatabasename }}:
      schemas:
        {{ .Values.postgres.schema }}: {}
      extensions:
        pg_partman: {{ .Values.postgres.schema }}
        postgis: {{ .Values.postgres.schema }}
    {{ .Values.postgres.geonodedatabase }}:
      schemas:
        {{ .Values.postgres.schema }}: {}
      extensions:
        pg_partman: {{ .Values.postgres.schema }}
        postgis: {{ .Values.postgres.schema }}
  postgresql:
    version: {{ .Values.postgres_operator_manifest.postgres_version | quote }}
