{{ if .Values.postgres.external_postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-geonode-external-secrets
type: Opaque
data:
  username: {{ .Values.postgres.username | quote }}
  password: {{ .Values.postgres.external_postgres.geonode_password | b64enc }}
{{ end }}
