{{ if .Values.postgres.external_postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-geodata-external-secrets
type: Opaque
data:
  username: {{ .Values.postgres.geodatabasename_and_username | quote }}
  password: {{ .Values.postgres.external_postgres.geodata_password | b64enc }}
{{ end }}
